name: Test User Service App

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Getting repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Getting permissions to execute the gradlew file
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew test

      - name: Run Build
        run: ./gradlew build